image: golang:latest

variables:
  REPO_NAME: gitlab.com/JanMa/correlation

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - go get github.com/google/uuid
  - go get github.com/lucsky/cuid
  - go get github.com/urfave/negroni

stages:
    - test
    - benchmark

format:
    stage: test
    script:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - go test $(go list ./... | grep -v /vendor/)
    stage: benchmark
    script:
      - go test -bench=. $(go list ./... | grep -v /vendor/)